// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// dac_i2s //
// ------- //

#define dac_i2s_wrap_target 0
#define dac_i2s_wrap 11
#define dac_i2s_pio_version 1

static const uint16_t dac_i2s_program_instructions[] = {
            //     .wrap_target
    0xf83e, //  0: set    x, 30           side 3     
    0x7101, //  1: out    pins, 1         side 2 [1] 
    0x5801, //  2: in     pins, 1         side 3     
    0x1841, //  3: jmp    x--, 1          side 3     
    0x6101, //  4: out    pins, 1         side 0 [1] 
    0x4801, //  5: in     pins, 1         side 1     
    0xe83e, //  6: set    x, 30           side 1     
    0x6101, //  7: out    pins, 1         side 0 [1] 
    0x4801, //  8: in     pins, 1         side 1     
    0x0847, //  9: jmp    x--, 7          side 1     
    0x7101, // 10: out    pins, 1         side 2 [1] 
    0x5801, // 11: in     pins, 1         side 3     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dac_i2s_program = {
    .instructions = dac_i2s_program_instructions,
    .length = 12,
    .origin = -1,
    .pio_version = dac_i2s_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config dac_i2s_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dac_i2s_wrap_target, offset + dac_i2s_wrap);
    sm_config_set_sideset(&c, 2, false, false);
    return c;
}
#endif

