// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// mic_i2s //
// ------- //

#define mic_i2s_wrap_target 0
#define mic_i2s_wrap 11
#define mic_i2s_pio_version 1

static const uint16_t mic_i2s_program_instructions[] = {
            //     .wrap_target
    0xf83e, //  0: set    x, 30           side 3     
    0xa942, //  1: nop                    side 1 [1] 
    0x5801, //  2: in     pins, 1         side 3     
    0x1841, //  3: jmp    x--, 1          side 3     
    0xa142, //  4: nop                    side 0 [1] 
    0x5001, //  5: in     pins, 1         side 2     
    0xf03e, //  6: set    x, 30           side 2     
    0xa142, //  7: nop                    side 0 [1] 
    0x5001, //  8: in     pins, 1         side 2     
    0x1047, //  9: jmp    x--, 7          side 2     
    0xa942, // 10: nop                    side 1 [1] 
    0x5801, // 11: in     pins, 1         side 3     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program mic_i2s_program = {
    .instructions = mic_i2s_program_instructions,
    .length = 12,
    .origin = -1,
    .pio_version = mic_i2s_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config mic_i2s_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + mic_i2s_wrap_target, offset + mic_i2s_wrap);
    sm_config_set_sideset(&c, 2, false, false);
    return c;
}
#endif

// -------- //
// mic_mclk //
// -------- //

#define mic_mclk_wrap_target 0
#define mic_mclk_wrap 1
#define mic_mclk_pio_version 1

static const uint16_t mic_mclk_program_instructions[] = {
            //     .wrap_target
    0xe001, //  0: set    pins, 1                    
    0xe000, //  1: set    pins, 0                    
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program mic_mclk_program = {
    .instructions = mic_mclk_program_instructions,
    .length = 2,
    .origin = -1,
    .pio_version = mic_mclk_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config mic_mclk_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + mic_mclk_wrap_target, offset + mic_mclk_wrap);
    return c;
}
#endif

